djangobb_forum/urls.py
from django.conf.urls.defaults import *

from djangobb_forum import settings as forum_settings
from djangobb_forum import views as forum_views
from djangobb_forum.feeds import LastPosts, LastTopics, LastPostsOnForum,\
     LastPostsOnCategory, LastPostsOnTopic
     

urlpatterns = patterns('',

    # Forum
    url('^$', forum_views.index, name='index'),
    url('^(?P<forum_id>\d+)/$', forum_views.show_forum, name='forum'),
    url('^moderate/(?P<forum_id>\d+)/$', forum_views.moderate, name='moderate'),
    url('^search/$', forum_views.search, name='search'),
    url('^misc/$', forum_views.misc, name='misc'),

    # User
    url('^user/(?P<username>.*)/$', forum_views.user, name='forum_profile'),
    url('^users/$', forum_views.users, name='forum_users'),

    # Topic
    url('^topic/(?P<topic_id>\d+)/$', forum_views.show_topic, name='topic'),
    url('^(?P<forum_id>\d+)/topic/add/$', forum_views.add_post,
        {'topic_id': None}, name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/delete_posts/$', forum_views.delete_posts, name='delete_posts'),
    url('^topic/move/$', forum_views.move_topic, name='move_topic'),
    url('^topic/(?P<topic_id>\d+)/stick_unstick/(?P<action>[s|u])/$', forum_views.stick_unstick_topic, name='stick_unstick_topic'),
    url('^topic/(?P<topic_id>\d+)/open_close/(?P<action>[c|o])/$', forum_views.open_close_topic, name='open_close_topic'),

    # Post
    url('^topic/(?P<topic_id>\d+)/post/add/$', forum_views.add_post,
        {'forum_id': None}, name='add_post'),
    url('^post/(?P<post_id>\d+)/$', forum_views.show_post, name='post'),
    url('^post/(?P<post_id>\d+)/edit/$', forum_views.edit_post, name='edit_post'),
    url('^post/(?P<post_id>\d+)/delete/$', forum_views.delete_post, name='delete_post'),
    # Post preview
    url(r'^preview/$', forum_views.post_preview, name='post_preview'),

    # Subscription
    url('^subscription/topic/(?P<topic_id>\d+)/delete/$', forum_views.delete_subscription, name='forum_delete_subscription'),
    url('^subscription/topic/(?P<topic_id>\d+)/add/$', forum_views.add_subscription, name='forum_add_subscription'),
    
    # Feeds
    url(r'^feeds/posts/$', LastPosts(), name='forum_posts_feed'),
    url(r'^feeds/topics/$', LastTopics(), name='forum_topics_feed'),
    url(r'^feeds/topic/(?P<topic_id>\d+)/$', LastPostsOnTopic(), name='forum_topic_feed'),
    url(r'^feeds/forum/(?P<forum_id>\d+)/$', LastPostsOnForum(), name='forum_forum_feed'),
    url(r'^feeds/category/(?P<category_id>\d+)/$', LastPostsOnCategory(), name='forum_category_feed'),
)

### EXTENSIONS ###

# LOFI Extension
if (forum_settings.LOFI_SUPPORT):
    urlpatterns += patterns('',
        url('^lofi/$', forum_views.index, {'full':False}, name='lofi_index'),
        url('^(?P<forum_id>\d+)/lofi/$', forum_views.show_forum, {'full':False}, name='lofi_forum'),
        url('^topic/(?P<topic_id>\d+)/lofi/$', forum_views.show_topic, {'full':False}, name='lofi_topic'),
    )

# REPUTATION Extension
if (forum_settings.REPUTATION_SUPPORT):
    urlpatterns += patterns('',
        url('^reputation/(?P<username>.*)/$', forum_views.reputation, name='reputation'),
    )

# ATTACHMENT Extension
if (forum_settings.ATTACHMENT_SUPPORT):
    urlpatterns += patterns('',
        url('^attachment/(?P<hash>\w+)/$', forum_views.show_attachment, name='forum_attachment'),
    )

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

from sitemap import SitemapForum, SitemapTopic
from forms import RegistrationFormUtfUsername
from djangobb_forum import settings as forum_settings

# HACK for add default_params with RegistrationFormUtfUsername and backend to registration urlpattern
# Must be changed after django-authopenid #50 (signup-page-does-not-work-whih-django-registration)
# will be fixed
from django_authopenid.urls import urlpatterns as authopenid_urlpatterns

for i, rurl in enumerate(authopenid_urlpatterns):
    if rurl.name == 'registration_register':
        authopenid_urlpatterns[i].default_args.update({'form_class': RegistrationFormUtfUsername})

from registration.views import register
admin.autodiscover()

from app.models import profile_callback
from app.forms import RegForm

urlpatterns = patterns('',
    url(r'^account/', include(authopenid_urlpatterns)),
    url(r'^forum', include('djangobb_forum.urls', namespace='djangobb')),
    url(r'^accounts/', include('socialauth.urls')),
    url(r'^accts/', include('registration.urls')),
    url(r'^accts/register/$', register, {'form_class':RegForm, 'profile_callback':profile_callback}, name='registration_register'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^search/', include('haystack.urls')),
    #url(r'^sentry/', include('sentry.web.urls')),
)


urlpatterns += patterns('bjj.app.views',
    url(r'^$', 'home', name = 'home'),
    url(r'^add-post2$', 'add_post2', name='add_post2'),
    url(r'^add-post$', 'add_post', name='add_post'),
    url(r'^category/(?P<cat_id>\d+)/', 'category', name='category'),
    url(r'^edit-profile$', 'edit_profile', name='edit_profile'),
    url(r'^latest$', 'latest', name='latest'),
    url(r'^login$', 'login', name='login'),
    url(r'^logout$', 'logout', name='logout'),
    url(r'^post/(?P<post_id>\d+)/', 'single_post', name='single_post'),
    url(r'^post/upvote$', 'upvote', name = 'upvote'),
    url(r'^profile/(?P<user_name>.+)$', 'view_profile', name='view_profile'),
    url(r'^set-handle$', 'set_handle', name='set_handle'),
    url(r'^site-message$', 'site_message', name='site_message'),
    url(r'^top-contributers$', 'top_contributers', name='top_contributers'),
)

urlpatterns += patterns('bjj.poll.views',
    url(r'^poll/random/$', 'get_random', name='get_random'),
    url(r'^poll/(?P<pk>\d+)/widget$', 'get_poll_widget', name='get_poll_widget'),
    url(r'^poll/(?P<pk>\d+)/', 'get_poll_single', name='get_poll_single'),
    url(r'^poll/choice/(?P<pk>\d+)/upvote$', 'upvote_choice', name='upvote_choice'),
    url(r'^poll/$', 'poll_index', name='poll_index'),
    url(r'^poll/add$', 'add_poll', name='add_poll'),
)
# PM Extension
if (forum_settings.PM_SUPPORT):
    urlpatterns += patterns('',
        (r'^pm/', include('messages.urls')),
   )

if (settings.DEBUG):
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

BELT_CHOICES = (
    ('White', 'White'),
    ('Blue', 'Blue'),
    ('Purple', 'Purple'),
    ('Brown', 'Brown'),
    ('Black', 'Black'),
)

class Category(models.Model):
    name = models.CharField(db_index = True, max_length=30)
    url_name = models.CharField(db_index = True, blank=True, max_length=30)
    seo_name = models.CharField(max_length=30,blank=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.url_name = self.name.replace(' ','-').replace('/','-').replace('#','-sharp')
        super(Category, self).save(*args, **kwargs) # Call the "real" save() method.    

    class Meta:
        ordering = ['name']

class Tag(models.Model):
    name = models.CharField(db_index = True, max_length=30)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, related_name='main_post')
    title = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80)
    is_youtube = models.BooleanField(default=False)
    post_url = models.URLField('Link to share', blank = True, verify_exists=False)
    text = models.TextField(blank = True, help_text = "Add some commentary for your link or just say what's on your mind")
    category = models.ForeignKey(Category, null=True, blank = True)
    upvotes = models.IntegerField(null=True, blank=True, max_length=4, default=0)
    #related_cats = models.ManyToManyField(Category, verbose_name = 'Related Categories', null=True, blank=True, related_name = 'rel_cats')
    datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/post/%s/%s" % (self.pk, self.slug)

    def check_youtube(self):
        if self.post_url[0:22] == 'http://www.youtube.com' or self.post_url[0:15] == 'http://youtu.be':
            return True
        return False
 
    def save(self):
        if not self.id:
            self.slug = slugify(self.title)
            self.is_youtube = self.check_youtube()
        super(Post, self).save()

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    handle = models.CharField(max_length=30, unique=True)
    email = models.EmailField(blank=True)
    bio = models.TextField(blank=True)
    points = models.IntegerField(max_length=7, default=0)
    upvoted = models.ManyToManyField(Post, related_name='upvoted_set')
    belt = models.CharField(default='White', max_length='10', choices=BELT_CHOICES)

    def __unicode__(self):
        return self.handle

    def get_absolute_url(self):
        return "/profile/%s" % self.handle

def profile_callback(user):
    profile = UserProfile.objects.create(user=user, handle=user.username)

templates/add_post.html
{% extends "base.html" %}

{% load uni_form_tags %}

{% block title %}
{{title}} | {{ block.super }}
{% endblock %}

{% block content %}
<form class="uniForm" action="{% url add_post %}" method="post"> {% csrf_token %}
{{ form|as_uni_form }}
<p>Your post will appear within 1 minute of submitting this form</p>
<p><input type="submit" class="myButton" value="Submit"></p>
</form>
{% endblock %}

templates/add_post2.html
{% extends "base2.html" %}

{% load uni_form_tags %}

{% block extrahead %}
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
<script>
$(".nav li").hover( function() {$(this).find("ul").show()}, function() {$(this).find("ul").hide()});
</script>
{% endblock %}

{% block title %}
{{title}} | {{ block.super }}
{% endblock %}
{% block content %}
<form class="uniForm" action="{% url add_post %}" method="post"> {% csrf_token %}
{{ form1|as_uni_form }}
<p><input type="submit" class="myButton" value="Submit"></p>

<form class="uniForm" action="{% url add_post %}" method="post"> {% csrf_token %}
{{ form2|as_uni_form }}
<p><input type="submit" class="myButton" value="Submit"></p>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="Best BJJ Links or Brazilian Jiu Jitsu Links" />
        <meta name="keywords" content="BJJ links, brazilian jiu jitsu links, BJJ, brazilian jiu jitsu, mma, jiu jitsu techniques, jiu jitsu moves" />
        <title>{% block title %}bjj links{% endblock %}</title>

<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/reset.css" />
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/style.css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script> 
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script> 
<script type="text/javascript" src="{{ MEDIA_URL }}js/openid-jquery.js"></script> 
<script type="text/javascript" src="{{ MEDIA_URL }}js/all2.js"></script>

{% block extrahead %}
{% endblock %}

<script type="text/javascript">

  var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-12460479-19']);
    _gaq.push(['_trackPageview']);

  (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();

</script>        
    </head>

<body class="docs" id="default">
<div id="fb-root"></div> 
<script>
var auth = {% if user.is_authenticated %}1{% else %}0{% endif %};
var path = "{{request.path}}";
FB.init({
    appId  : '204008706318192',
    status : true, // check login status
    cookie : true, // enable cookies to allow the server to access the session
    xfbml  : true  // parse XFBML
});
</script>    
        <div class="wrapper">
<center>
<div id="ads">
    <table>
        <tr>
        <td>
        <!-- Begin: adBrite, Generated: 2011-09-15 0:42:11  -->
<script type="text/javascript">
var AdBrite_Title_Color = '2869A9';
var AdBrite_Text_Color = '444444';
var AdBrite_Background_Color = 'F1F1F2';
var AdBrite_Border_Color = 'CCCCCC';
var AdBrite_URL_Color = '699C06';
try{var AdBrite_Iframe=window.top!=window.self?2:1;var AdBrite_Referrer=document.referrer==''?document.location:document.referrer;AdBrite_Referrer=encodeURIComponent(AdBrite_Referrer);}catch(e){var AdBrite_Iframe='';var AdBrite_Referrer='';}
</script>
<span style="white-space:nowrap;"><script type="text/javascript">document.write(String.fromCharCode(60,83,67,82,73,80,84));document.write(' src="http://ads.adbrite.com/mb/text_group.php?sid=2013171&zs=3732385f3930&ifr='+AdBrite_Iframe+'&ref='+AdBrite_Referrer+'" type="text/javascript">');document.write(String.fromCharCode(60,47,83,67,82,73,80,84,62));</script>
<a target="_top" href="http://www.adbrite.com/mb/commerce/purchase_form.php?opid=2013171&afsid=1"><img src="http://files.adbrite.com/mb/images/adbrite-your-ad-here-leaderboard.gif" style="background-color:#CCCCCC;border:none;padding:0;margin:0;" alt="Your Ad Here" width="14" height="90" border="0" /></a></span>
<!-- End: adBrite -->
</td>
        <td><img src="/media/images/bjjlinkslogo.png" /></td>
        </tr>
    </table>
</div>
</center>
<nav>
    <ul class="nav">
        <li><a id="poll" class="navEffect" href="{% url poll_index %}">Polls</a></li>
        {% if user.is_authenticated %}
        <li><a id="add_post" class="navEffect" href="{% url add_post %}">Add Post</a></li>
        <li><a id="add_poll" class="navEffect" href="{% url add_poll %}">Add Poll</a></li>
        {% endif %}
        <li><a id="top" class="navEffect" href="{% url top_contributers %}">Users</a></li>
        <li><a id="search" class="navEffect" href="{% url haystack_search %}">Search</a></li>
    </ul>
    <div class="clear"></div>
</nav>
            
            <header>
                <div id="header-content">
                    <a id="home" class="home" href="/">Top</a> |
                    <a id="latest" class="navEffect" href="{% url latest %}">Latest</a> |
            {% for cat in cats %}
                <a href="{% url category cat.pk %}{% firstof cat.seo_name|slugify cat.name|slugify %}">{{cat.name}} </a>{% if not forloop.last %}|{% endif %} 
            {% endfor %}
                </div>
            </header>
            
            <div id="main_content">
                
<div class="docs-content">
    <div class="main-col">
        <div class="section min" id="introduction">
    <center>{% block page_title %}<h2>{{title}}</h2>{% endblock %}</center>
        <hr id="ti" />
        {% for message in messages %}
        <p>{{ message }}</p>
        <hr id="ti" />
        {% endfor %}
   {% block content %}{% endblock %}
        </div>
    </div>
    
    <aside style="margin-top:70px" class="sidebar">
        {% if user.is_authenticated %}
            {% if handle_form %}
            <h5>Welcome</h5>
            <hr />
                <form method="post" action="{% url set_handle %}"> {% csrf_token %} 
                    <p>Set your username: {{handle_form.handle}} <input type="submit" value="Submit" /></p>
                </form>
            {% else %}
            <h5>Welcome <b>{{user.get_profile.handle}}</b></h5>
            <hr />
               You have <span id="pts" class="yellow">{{user.get_profile.points}}</span> points.
               </p>
               <p class="right-align">
<a href="{% url edit_profile %}">Edit profile</a> |
                <a href="{% url socialauth_social_logout %}" onclick="return logoutFb()">Logout</a>
                </p>
                <br clear="both" />
            {% endif %}
        {% else %}
        <h5>Login or Register</h5>
          <hr />
<p>
<a href="{{ FB_LOGIN_URL|safe}}">
             <img style="margin:0px;padding:0px;" src="{{MEDIA_URL}}icons/facebook-32.png" />
           </a>
            <a href="http://{{DOMAIN}}/accounts/openid/?action=verify&openid_next=%2F&openid_identifier=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid"><img src="{{MEDIA_URL}}icons/google-32.png" /></a>
            <a href="{% url socialauth_linkedin_login %}?next=/">
                <img src="{{MEDIA_URL}}icons/linkedin-32.png" />
            </a> 
            <a href="{% url socialauth_twitter_login %}">
                <img src="{{MEDIA_URL}}icons/twitter-32.png" />
            </a>
</p>        <a id="register" class="navEffect" href="{% url registration_register %}">Register</a> or login <a id="login" class="" href="{% url login %}">here</a>
        {% endif %}
    </aside>
    <aside class="sidebar">
        <h5>Popular Polls</h5>
        <hr />
        {% for poll in top_polls %}         
        <p><a href="{% url get_poll_single poll.id %}">{{poll.question}}</a></p>
        {% endfor %}
    </aside>
    <aside class="sidebar">
        <h5>Most Discussed</h5>
        <hr />
        {% for post in most_discussed %}
        {% with post.1|slugify as slug %}
        <p><a href="/post/{{post.0}}/{{slug}}">{{post.1}}</a></p>
        {% endwith %}
        {% endfor %}
    </aside>

</div>
<div class="clear"></div>
            </div>
            <div class="push"></div>
        </div>
<center>
<div id="ads-bot">
<!-- Begin: adBrite, Generated: 2011-09-15 0:42:11  -->
<script type="text/javascript">
var AdBrite_Title_Color = '2869A9';
var AdBrite_Text_Color = '444444';
var AdBrite_Background_Color = 'F1F1F2';
var AdBrite_Border_Color = 'CCCCCC';
var AdBrite_URL_Color = '699C06';
try{var AdBrite_Iframe=window.top!=window.self?2:1;var AdBrite_Referrer=document.referrer==''?document.location:document.referrer;AdBrite_Referrer=encodeURIComponent(AdBrite_Referrer);}catch(e){var AdBrite_Iframe='';var AdBrite_Referrer='';}
</script>
<span style="white-space:nowrap;"><script type="text/javascript">document.write(String.fromCharCode(60,83,67,82,73,80,84));document.write(' src="http://ads.adbrite.com/mb/text_group.php?sid=2013171&zs=3732385f3930&ifr='+AdBrite_Iframe+'&ref='+AdBrite_Referrer+'" type="text/javascript">');document.write(String.fromCharCode(60,47,83,67,82,73,80,84,62));</script>
<a target="_top" href="http://www.adbrite.com/mb/commerce/purchase_form.php?opid=2013171&afsid=1"><img src="http://files.adbrite.com/mb/images/adbrite-your-ad-here-leaderboard.gif" style="background-color:#CCCCCC;border:none;padding:0;margin:0;" alt="Your Ad Here" width="14" height="90" border="0" /></a></span>
<!-- End: adBrite -->
</div>
</center>
    </body>
</html>

templates/categorize.html
{% extends "base.html" %}

{% block content %}
<div class="gen-content-l">

{% if uncat_post %}
<h3>~ {{num_uncat}} uncategorized</h3>

<a href="{{uncat_post.post_url}}" class="yellow">{{uncat_post.title}}</a>
<form id="uncat_form"  action="{% url categorize %}" method="post"> {% csrf_token %}
<input type="hidden" value="{{uncat_post.id}}" name="post_id">
<p><label for="id_category">Primary Category:</label>
<select name="category" id="id_category">
</select>
</p>
<input type="submit" value="Categorize!" /> 
</p>
</form>
{% else %}
No content
{% endif %}
</div>
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<form action="{% url edit_profile %}" method="post"> {% csrf_token %}
{{form.as_p}}
<input class="myButton" type="submit" value="Submit"/>
{% endblock %}

templates/generic_posts.html
{% extends "base.html" %}

{% block title %}
{{title}} | {{block.super}}
{% endblock %}
{% block extrahead %}
<script>
var page_num = {{page}};
</script>
{% endblock %}

{% block content %}
{% if posts %}

{% include "generic_table.html" %}
<hr />
<div id="pagination" class="bottom">
{% include "pagination.html" %}
</div>
<!-- end pagination --> 
{% else %}
<div id="no-content" class="min">No content.</div>
{% endif  %}
{% endblock %}

templates/generic_table.html
{% load comments %}

<table id="p-t" border="0">
    <tbody id="posts">
        {% for post in posts %}
        {% get_comment_count for post as comment_count %}
        <tr>
            <td class="rank"></td>
            <td class="cell"><a href="{% if post.is_youtube %}/post/{{post.id}}/{{post.title|slugify}}{% else %}{{post.post_url}}" target="blank{% endif %}">{{ post.title }}</a></td>
            <td id="{{post.id}}" class="green">+{{ post.upvotes }}</td>
            <td><a href="/post/{{post.id}}/{{post.title|slugify}}#comments" class="yellow comm">{{ comment_count }} comments</a> <span class="comm"> by </span> <a href="/profile/{{post.author.get_profile.handle}}" class="name">{{ post.author.get_profile.handle }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/login.html
{% extends "base.html" %}

{% block title %}
login | {{ block.super }}
{% endblock %}
{% block content %}
<div class="gen-content-l">
<form action="{% url login %}" method="post"> {% csrf_token %}
{{form.as_p}} 
<input type="submit" class="myButton" value="Submit" />
</form>
</div>
{% endblock %}

templates/pagination.html
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}

templates/single_post.html
{% extends "base.html" %}

{% block title %}
{{post.title}} | {% firstof cat.seo_name cat.name %} | {{ block.super }} 
{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
<script>
var page_num = 0;
var post_url = "{{post.post_url|safe}}";

</script>
{% endblock %}

{% block page_title %}
<div id="post_title">
<table>
    <tbody id="posts">
    <tr>
        <td><div id="v{{post.id}}" class="thumb" onclick="return upvotePost({{post.id}})"></div></td>
        <td><h2><span id="{{post.id}}" class="gr">+{{post.upvotes}}</span></h2></td>
        <td><h2>{{title}}</h2></td>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

{% block content %}
{% if not post.is_youtube %} <a href="{{ post.post_url }}" target="blank">{{ post.post_url }}</a>{% endif %}
{% if post.text %}<br /><p>{{post.text}}</p>{% endif %}
<br />

<div class="comments">
{% with post as object %}
    {% include "partial/comment.html" %}
{% endwith %}
</div>

{% endblock %}

templates/site_message.html
{% extends "base.html" %}

{% block content %}
<div id="messages">
{% for message in messages %}
    {{message}}
{% endfor %}
</div>
{% endblock %}

templates/top_contributers.html
{% extends "base.html" %}

{% block title %}
{{ title }} | {{ block.super }}
{% endblock %}
{% block content %}
<center>
<table style="max-width:700px;" border="0">
    <thead>
        <tr><th></th><th>user</th><th>points</th><th>belt</th></tr>
    </thead>
    <tbody>
    {% for profile in profiles %}
        <tr><td>{{forloop.counter}}</td><td><a href="{% url view_profile profile.handle %}">{{profile.handle}}</a></td><td>{{profile.points}}</td><td>{{ profile.belt }}</td></tr>
    {% endfor %}
    </tbody>
</table>    
</center>
{% endblock %}

templates/view_profile.html
{% extends "base.html" %}

{% block title %}
{{profile.handle}}'s profile | {{ block.super }}
{% endblock %}
{% block content %}
<p><b>Belt:</b> {{ profile.belt }}</p>
<p><b>Bio:</b> {% firstof profile.bio "None"%}</p>
{% endblock %}